otel:
  # your logz.io region
  logzio_region: "us"
  # custom listener address
  custom_listener: ""
  # environment tag that will be attached to all samples
  p8s_logzio_name: "postgres-observability"
  # your logz.io metrics token
  token: token
  # the time to wait between scrape requests
  remote_timeout: 120
  # opentelemetry log level
  log_level: "debug"
  # python script log level
  logzio_log_level: "debug"
pg:
  # pg scrape interval
  pg_scrape_interval: 60
  # pg scrape timeout
  pg_scrape_timeout: 120
  # list of instances to monitor
  instances: []
