exporters:
  logging:
    loglevel: info
  prometheusremotewrite:
    endpoint: https://listener.logz.io:8053
    external_labels:
      p8s_logzio_name:
    headers:
      Authorization: Bearer
    timeout: 120s
extensions:
  health_check: null
  pprof: null
  zpages: null
processors: null
receivers: {}

service:
  extensions:
  - health_check
  - pprof
  - zpages
  pipelines:
    metrics:
      exporters:
      - logging
      - prometheusremotewrite
      processors: []
      receivers: []
  telemetry:
    logs:
      level: debug
