exporters:
  logging:
    loglevel: info
  prometheusremotewrite:
    endpoint: https://listener.logz.io:8053
    external_labels:
      p8s_logzio_name:
    headers:
      Authorization: Bearer
    timeout: 120s
extensions:
  health_check: null
  pprof: null
  zpages: null
processors: null
receivers:
  prometheus_exec/postgres:
    exec: ./postgres_exporter
    scrape_interval: 60s
    port: 9187
    env:
      - name: PG_EXPORTER_DISABLE_DEFAULT_METRICS
        value: "true"
      - name: PG_EXPORTER_EXTEND_QUERY_MR_PATH
        value: "queries/"
      - name: PG_EXPORTER_EXTEND_QUERY_MR
        value: "true"

service:
  extensions:
  - health_check
  - pprof
  - zpages
  pipelines:
    metrics:
      exporters:
      - logging
      - prometheusremotewrite
      processors: []
      receivers:
      - prometheus_exec/postgres
  telemetry:
    logs:
      level: debug
